#!/usr/bin/env ruby

require 'socket'

port = ARGV[0].to_i

server = UDPSocket.new.tap do |s|
  s.bind("127.0.0.1", port)
  $stderr.puts "Listening on port #{port}..."
end

loop do
  p server.recvmsg
end
